#pragma once
// FFT ocean (track W, B7; FEATURES_GAME 1; kernels Ocean.hlsli): three periodic cascades of 512^2, each holding its own
// band of a JONSWAP sea with directional spreading, evolved by deep-water dispersion and inverse-FFT'd every frame into
// displacement (Dx, h, Dz), slopes and the horizontal-displacement derivatives (tangents, Jacobian for foam) per texel,
// with a full mip chain (the low-pass a coarser vertex spacing or pixel footprint sees) and the previous frame's
// displacement (motion: V's triangle stream velocities).
#include "unx/render/Device.h"
#include "unx/render/RenderGraph.h"
#include "unx/render/Shaders.h"

#include <cstdint>
#include <vector>

namespace unx::water
{
struct OceanDesc
{
    float lengths[3] = { 1024.0f, 128.0f, 16.0f };  // tile sizes (m), largest first
    // Band boundaries (1/m): cascade 0 holds |k| < bands[0], 1 holds [bands[0], bands[1]), 2 holds |k| >= bands[1].
    // Each boundary must lie below the coarser cascade's Nyquist pi N / L (the band is a full annulus in its grid).
    float bands[2] = { 1.0f, 8.0f };
    float windSpeed = 10.0f;      // U at 10 m (m/s)
    float fetch = 100000.0f;      // F (m)
    float windDirection = 0.0f;   // radians from +x towards +z: the direction the waves travel
    float spread = 8.0f;          // s of cos^(2s)(theta / 2)
    uint32_t seed = 1;
};
struct OceanOutput
{
    // RGBA32F texture arrays, 512^2 with 10 mips, slice c = cascade c; texel (x, z) of mip 0 is the rest position
    // (x, z) L_c / 512 of the periodic tile (mip m: texel centres at (x + 0.5) 2^m - 0.5); metres.
    //   displacement: (Dx, h, Dz, dDx/dz)       slopes: (dh/dx, dh/dz, dDx/dx, dDz/dz)
    // Jacobian J = (1 + dDx/dx)(1 + dDz/dz) - (dDx/dz)^2; tangents (1 + dDx/dx, dh/dx, dDx/dz), (dDx/dz, dh/dz, 1 + dDz/dz).
    render::TextureRef displacement, slopes;
    render::TextureRef previousDisplacement;  // the previous record's displacement (same layout)
    bool previousValid = false;               // false on the first record and after a new sea state or spectrum
    render::BufferRef h0;                     // the persistent initial spectrum, float4 per bin (Ocean.hlsli)
};

class Ocean
{
public:
    static constexpr uint32_t kN = 512, kCascades = 3, kMips = 10;
    static constexpr double kRepeat = 4096.0;  // dispersion repeat period T (s), Ocean.hlsli
    Ocean(render::Device& device, render::ShaderLibrary& shaders, const OceanDesc& desc);
    ~Ocean();
    Ocean(const Ocean&) = delete;
    Ocean& operator=(const Ocean&) = delete;

    // A new sea state: the initial spectrum is regenerated by the next record.
    void setDesc(const OceanDesc& desc);
    // An explicit initial spectrum instead of the sea state's (authoring, tests): kCascades N^2 float4 per bin,
    // (h0(k), conj(h0(-k))) at bin index (x, z) with k = 2 pi ((x, z) - N / 2) / L. Uploaded by the next record.
    void setSpectrum(const std::vector<float>& h0);
    // Records the frame's evolution, inverse FFTs and mip chain at game time `seconds` (compute on the graphics queue).
    // The textures are the module's own (persistent, ping-ponged displacement), imported into this graph.
    OceanOutput record(render::RenderGraph& graph, double seconds);
    const OceanDesc& desc() const { return m_desc; }

    // The phase clock: u = frac(t / T) 2^32 (Ocean.hlsli oceanPhase) and the quantised angular frequency of |k|.
    static uint32_t phaseClock(double seconds);
    static uint32_t frequencyIndex(double kLength);

private:
    render::Device& m_device;
    render::ShaderLibrary& m_shaders;
    OceanDesc m_desc;
    render::ComPtr<ID3D12Resource> m_h0, m_frequencies, m_twiddles, m_upload, m_frequencyUpload;
    render::ComPtr<ID3D12Resource> m_textures[3];  // displacement (ping-pong 0, 1), slopes
    uint32_t m_uav[3][kMips] = {};                 // per-mip UAVs (the graph's views cover mip 0)
    uint32_t m_current = 0;                        // displacement texture written by the next record
    bool m_dirty = true, m_explicit = false, m_frequenciesDirty = true, m_previousValid = false;
};
} // namespace unx::water
