# Generates Native/Scene/src/ThinFilmTables.inc: the constant data of the A9 thin film definition (MATERIAL_LAYERS 1.2,
# method (c) with 32 bins, Results/C/MaterialLayers/REPORT_R2_KO.md 3): the bins (uniform in wavenumber over the CIE 1931
# 2 deg support 360-830 nm), each bin's colour weight (its CMF sums over 1 nm, / sum y, XYZ -> linear Rec.709
# white-balanced to illuminant E, so constant reflectance R gives (R, R, R)), and the substrate presets' spectral n + ik
# at the bin centres (linear in wavelength, as the study's Substrate::at). Data: Reference/Studies/data (README there).
#   python Native/Scene/Tools/ThinFilmTables.py
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
DATA = os.path.join(ROOT, 'Reference', 'Studies', 'data')
BINS = 32
PRESETS = [('gold', 'Au_johnson_christy_um_n_k.txt'), ('copper', 'Cu_johnson_christy_um_n_k.txt'),
           ('silver', 'Ag_johnson_christy_um_n_k.txt'), ('aluminium', 'Al_rakic_um_n_k.txt'),
           ('iron', 'Fe_johnson_christy_um_n_k.txt')]

cmf = []
for line in open(os.path.join(DATA, 'cie1931_2deg_xyz_1nm.csv')):
    p = line.strip().split(',')
    if len(p) == 4:
        try: cmf.append(tuple(float(x) for x in p))
        except ValueError: pass
white = [sum(c[i] for c in cmf) for i in (1, 2, 3)]
sumY = white[1]
white = [w / sumY for w in white]
S = [[3.2404542, -1.5371385, -0.4985314], [-0.9692660, 1.8760108, 0.0415560], [0.0556434, -0.2040259, 1.0572252]]
M = [[S[r][c] / sum(S[r][k] * white[k] for k in range(3)) for c in range(3)] for r in range(3)]

lam0, lam1 = cmf[0][0], cmf[-1][0]
k0, k1 = 1 / lam1, 1 / lam0
edges = [1 / (k1 - (k1 - k0) * b / BINS) for b in range(BINS + 1)]
weights = []
for b in range(BINS):
    lo, hi = edges[b], edges[b + 1]
    xyz = [0.0, 0.0, 0.0]
    for c in cmf:
        if c[0] >= lo and (c[0] < hi or b == BINS - 1):
            for i in range(3): xyz[i] += c[i + 1]
    xyz = [v / sumY for v in xyz]
    weights.append([sum(M[r][i] * xyz[i] for i in range(3)) for r in range(3)])

def metal(path):
    rows = [tuple(float(x) for x in l.split()) for l in open(os.path.join(DATA, path)) if l.strip()]
    def at(nm):
        l = nm * 1e-3
        i = 1
        while i + 1 < len(rows) and rows[i][0] < l: i += 1
        t = min(max((l - rows[i - 1][0]) / (rows[i][0] - rows[i - 1][0]), 0.0), 1.0)
        return rows[i - 1][1] + t * (rows[i][1] - rows[i - 1][1]), rows[i - 1][2] + t * (rows[i][2] - rows[i - 1][2])
    return [at(0.5 * (edges[b] + edges[b + 1])) for b in range(BINS)]

out = ['// Generated by Native/Scene/Tools/ThinFilmTables.py - do not edit. A9 thin film (MaterialModel.h filmReflectance).',
       'constexpr uint32_t kFilmTableBins = %d;' % BINS,
       '// bin edges (nm), increasing: bin b is [kFilmBinEdges[b], kFilmBinEdges[b + 1])',
       'constexpr float kFilmBinEdges[%d] = { %s };' % (BINS + 1, ', '.join('%.6ff' % e for e in edges)),
       '// linear Rec.709 (E) weight of each bin: rgb = sum_b R_b w_b',
       'constexpr float kFilmBinWeights[%d][3] = {' % BINS]
out += ['    { %.9ff, %.9ff, %.9ff },' % tuple(w) for w in weights]
out += ['};', '// substrate presets (MaterialFilmSubstrate 1..%d): n, k at the bin centres' % len(PRESETS),
        'constexpr float kFilmPresetNk[%d][%d][2] = {' % (len(PRESETS), BINS)]
for name, path in PRESETS:
    out.append('    { // %s (%s)' % (name, path))
    out += ['        { %.6ff, %.6ff },' % nk for nk in metal(path)]
    out.append('    },')
out.append('};')
open(os.path.join(ROOT, 'Native', 'Scene', 'src', 'ThinFilmTables.inc'), 'w', newline='\n').write('\n'.join(out) + '\n')
print('sum of weights', [round(sum(w[i] for w in weights), 6) for i in range(3)])
