# Folder auto-registration (INTERFACES_KO.md 2). Tracks add code by adding files inside the folders they own; no shared
# CMakeLists.txt changes.
#
# Render module = Native/Render/Passes/<Name> or Native/Render/RayTracing:
#   *.cpp (recursive, except Tests/ and Gates/)  -> static library unx_module_<name>   (links unx_render, unx_scene)
#   include/                                      -> public include directory of that library
#   module.cmake (optional)                       -> included with UNX_MODULE_TARGET / UNX_MODULE_DIR set (extra deps)
#   Tests/*.cpp                                   -> one executable each: unx_test_<name>_<file>   (correctness, no GPU lock)
#   Gates/*.cpp                                   -> one executable each: unx_gate_<name>_<file>   (measurement, GPU lock)
#   *.hlsl                                        -> kernels named by path relative to Native/Render (Shaders.cmake)
# Tool = Tools/<Name>/CMakeLists.txt (except standalone projects), Reference/CMakeLists.txt: added as subdirectories.
# Folders of disabled tracks (cmake/Tracks.cmake, UNX_TRACKS) are skipped.
include_guard(GLOBAL)

set_property(GLOBAL PROPERTY UNX_RENDER_MODULES "")
set_property(GLOBAL PROPERTY UNX_MODULE_EXECUTABLES "")

function(unx_register_render_module dir)
  get_filename_component(folder "${dir}" NAME)
  string(TOLOWER "${folder}" name)
  set(target unx_module_${name})
  file(GLOB_RECURSE all_sources CONFIGURE_DEPENDS "${dir}/*.cpp")
  set(sources)
  foreach(src ${all_sources})
    file(RELATIVE_PATH rel "${dir}" "${src}")
    if(NOT rel MATCHES "^(Tests|Gates)/")
      list(APPEND sources "${src}")
    endif()
  endforeach()
  if(sources)
    add_library(${target} STATIC ${sources})
    unx_target_defaults(${target})
    target_link_libraries(${target} PUBLIC unx_render unx_scene)
    target_include_directories(${target} PRIVATE "${dir}")
    if(EXISTS "${dir}/include")
      target_include_directories(${target} PUBLIC "${dir}/include")
    endif()
    set_property(GLOBAL APPEND PROPERTY UNX_RENDER_MODULES ${target})
  endif()
  set(UNX_MODULE_NAME ${name})
  set(UNX_MODULE_TARGET ${target})
  set(UNX_MODULE_DIR "${dir}")
  if(EXISTS "${dir}/module.cmake")
    include("${dir}/module.cmake")
  endif()
  foreach(kind Tests Gates)
    file(GLOB exes CONFIGURE_DEPENDS "${dir}/${kind}/*.cpp")
    string(TOLOWER "${kind}" lower)
    string(REGEX REPLACE "s$" "" prefix "${lower}")
    foreach(exe ${exes})
      get_filename_component(stem "${exe}" NAME_WE)
      string(TOLOWER "${stem}" stem)
      set_property(GLOBAL APPEND PROPERTY UNX_MODULE_EXECUTABLES "unx_${prefix}_${name}_${stem}|${exe}|${dir}")
    endforeach()
  endforeach()
endfunction()

# Executables of module Tests/ and Gates/ link the whole renderer; created after unx_renderer exists.
function(unx_create_module_executables)
  get_property(entries GLOBAL PROPERTY UNX_MODULE_EXECUTABLES)
  foreach(entry ${entries})
    string(REPLACE "|" ";" parts "${entry}")
    list(GET parts 0 exe_name)
    list(GET parts 1 exe_source)
    list(GET parts 2 exe_dir)
    unx_add_executable(${exe_name} "${exe_source}")
    target_link_libraries(${exe_name} PRIVATE unx_renderer)
    target_include_directories(${exe_name} PRIVATE "${exe_dir}")
    target_compile_definitions(${exe_name} PRIVATE UNX_SOURCE_DIR="${CMAKE_SOURCE_DIR}")
  endforeach()
endfunction()

# Tools/* and Reference: every folder with a CMakeLists.txt, except standalone projects built on their own.
function(unx_add_tool_folders)
  set(standalone Microbench ShaderCompiler)
  file(GLOB dirs LIST_DIRECTORIES true "${CMAKE_SOURCE_DIR}/Tools/*")
  foreach(d ${dirs})
    get_filename_component(n "${d}" NAME)
    if(IS_DIRECTORY "${d}" AND EXISTS "${d}/CMakeLists.txt" AND NOT n IN_LIST standalone)
      unx_folder_enabled(${n} folder_on)
      if(folder_on)
        add_subdirectory("${d}" "${CMAKE_BINARY_DIR}/Tools/${n}")
      endif()
    endif()
  endforeach()
  unx_folder_enabled(Reference folder_on)
  if(folder_on AND EXISTS "${CMAKE_SOURCE_DIR}/Reference/CMakeLists.txt")
    add_subdirectory("${CMAKE_SOURCE_DIR}/Reference" "${CMAKE_BINARY_DIR}/Reference")
  endif()
endfunction()
