# cmake -P script: writes the build identity header only when its content changes.
execute_process(COMMAND git -C "${SOURCE_DIR}" rev-parse HEAD OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
execute_process(COMMAND git -C "${SOURCE_DIR}" status --porcelain --untracked-files=no OUTPUT_VARIABLE status OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
set(dirty 0)
set(diffhash "")
if(NOT status STREQUAL "")
  set(dirty 1)
  execute_process(COMMAND git -C "${SOURCE_DIR}" diff HEAD OUTPUT_VARIABLE diff ERROR_QUIET)
  string(SHA256 diffhash "${diff}")
  string(SUBSTRING "${diffhash}" 0 16 diffhash)
endif()
if(NOT commit)
  set(commit "unknown")
endif()
set(content "// Generated by cmake/WriteBuildIdentity.cmake. Do not edit.
#pragma once
#define UNX_BUILD_COMMIT \"${commit}\"
#define UNX_BUILD_DIRTY ${dirty}
#define UNX_BUILD_DIFF_SHA256 \"${diffhash}\"
#define UNX_AGILITY_PACKAGE_VERSION \"${AGILITY}\"
#define UNX_NVAPI_SDK_COMMIT \"${NVAPI}\"
")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
  file(WRITE "${OUT}" "${content}")
endif()
